server:
  port: 9667
spring:
  application:
    name: elves-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eastFu/spring-cloud-demo/
          username:
          password:
          search-paths: config
      label: master

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.12.53.58:9528/eureka/,http://10.12.53.58:9528/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
