server:
  port: 8000

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: elves-eureka1
    perfer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://east2:8000/eureka/