server:
  port: 9527
spring:
  application:
    name: elves-eureka-center1
#eureka.client.register-with-eureka ：表示是否将自己注册到Eureka Server，默认为true。
#eureka.client.fetch-registry ：表示是否从Eureka Server获取注册信息，默认为true。
#eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
#eureka.instance.prefer-ip-address 默认值为false,如果我们不想使用主机名来定义注册中心的地址，也可以用ip的形式，需要修改这个参数为true。
#eureka.server.serverenable-self-preservation: false 关闭保护机制
eureka:
  instance:
    hostname: center1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9528/eureka/